name: flutter_starter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-286.0.dev <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  envied: ^0.3.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_animated_icons: ^1.0.1
  icons_launcher: ^2.1.0
  quickalert: ^1.0.1
  sidebarx: ^0.15.0
  provider: ^6.0.3
  font_awesome_flutter: ^10.3.0
  http: ^0.13.6
  image_picker: ^0.8.5+3
  image_cropper: ^2.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3 # flutter pub run build_runner build
  json_serializable: ^6.6.0

flutter:
  uses-material-design: true
